"""criar tabelas

Revision ID: 200bb7f2b792
Revises: 
Create Date: 2026-06-18 17:54:03.985620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200bb7f2b792'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('steam_id', name=op.f('uq_usuario_steam_id'))
    )
    op.create_table('jogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('steam_appid', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_jogo_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jogo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogo')
    op.drop_table('usuario')
    # ### end Alembic commands ###
