"""multiplayer

Revision ID: 69cb381b11e5
Revises: 8a3ea2f36ee1
Create Date: 2026-08-20 17:38:12.439611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cb381b11e5'
down_revision = '8a3ea2f36ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempo_solo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tempo_coop', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tempo_vs', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.drop_column('tempo_vs')
        batch_op.drop_column('tempo_coop')
        batch_op.drop_column('tempo_solo')

    # ### end Alembic commands ###
