"""Add colunas HLTB

Revision ID: 8a3ea2f36ee1
Revises: 200bb7f2b792
Create Date: 2026-08-06 17:41:24.533850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3ea2f36ee1'
down_revision = '200bb7f2b792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempo_historia', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tempo_extra', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tempo_completo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.drop_column('tempo_completo')
        batch_op.drop_column('tempo_extra')
        batch_op.drop_column('tempo_historia')

    # ### end Alembic commands ###
